### ISSUE TITLE
New Feature: User customization via `.yaml` config file

### ISSUE THREAD

**Issue by giacomo-folli** [giacomo-folli/balls#1]
Consider allowing user customization via `.yaml` configuration file. It's useless now, but could come in handy for upcoming features.

### Example use case
- Set constants, adjust gravity or energy loss factor
- Customize ball colors or sizes

```yaml
# config.yaml

constants:
    gravity: 2.1
    e_loss: 0.98

balls:
    color: ...

noise:
    type: perlin
...
```

### Why
This would make the project more flexible and user-friendly without needing to change the code directly.
